### ISSUE TITLE
Sponsors: Add Code for Science and Society

### ISSUE THREAD

**Issue by kipkurui** [bioinformatics-hub-ke/BOSS22#2]
https://codeforscience.org/img/Blue-logo-black-text-stacked.png

**Comment by bkmgit** [comment]
Vector images are slightly better since they are resolution independent. EPS images can be converted to SVG, as described at https://superuser.com/questions/198460/converting-from-eps-to-svg-format 

Some EPS format logos are available at https://github.com/codeforscience/codeforscience.org/tree/live/src/public/img

**Comment by bkmgit** [comment]
@kipkurui Let me know if ok, added a logo.

**Comment by kipkurui** [comment]
All good, thanks @bkmgit
